### ISSUE TITLE
Empty array

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [gnahotelsolutions/laravel-weather#4]
Hello,
Is it possible to test this with localhost?

When I print:
`print_r($currentWeatherInGirona);`

I get what's looking like an empty array like:
`GuzzleHttp\Psr7\Stream Object ( [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #512 [size:GuzzleHttp\Psr7\Stream:private] => [seekable:GuzzleHttp\Psr7\Stream:private] => 1 [readable:GuzzleHttp\Psr7\Stream:private] => 1 [writable:GuzzleHttp\Psr7\Stream:private] => 1 [uri:GuzzleHttp\Psr7\Stream:private] => php://temp [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array ( ) )`

**Comment by Lloople** [comment]
Hi David,

This package returns a StreamInterface object.  If you want to see the data inside the response, you must cast it to string or to json:

```php
print_r(json_decode($currentWeatherInGirona));

// or

print_r((string)$currentWeatherInGirona);
```
